"""Write docs/ratios.md from the registries, so the page cannot drift from the code.

    python scripts/gen_ratio_docs.py            # rewrite docs/ratios.md
    python scripts/gen_ratio_docs.py --check    # exit 1 if the file is out of date (used by the tests and CI)

Run it in a fresh interpreter: anything a program registers at run time would otherwise appear.
"""
from __future__ import annotations

import sys
from pathlib import Path

from calcfinc.adapters import ind_as_xbrl
from calcfinc.registry import metrics, ratios

OUT = Path(__file__).resolve().parent.parent / "docs" / "ratios.md"

GROUPS = (("", "Generic"), ("bank", "Banks (`bank.*`)"), ("insurance", "Insurers (`insurance.*`)"),
          ("india", "Indian forms (`india.*`, after `ind_as_xbrl.register()`)"))
UNITS = {"pct": "percent", "x": "times", "currency": "amount", "per_share": "per share", "shares": "shares",
         "days": "days"}


def _cell(text: str) -> str:
    return text.replace("|", "\\|").replace("\n", " ")


def _code(text: str) -> str:
    return f"`{_cell(text)}`"


def _ratio_rows(group: str) -> list[str]:
    rows = []
    for name, spec in ratios.FORMULAS.items():
        ns = name.split(".")[0] if "." in name else ""
        if ns != group:
            continue
        aliases = [a for a, target in ratios.ALIASES.items() if target == name]
        notes = []
        if spec.optional:
            notes.append("treated as 0 when not reported: " + ", ".join(_code(o) for o in spec.optional))
        if spec.requires_positive:
            notes.append("must be positive: " + ", ".join(_code(o) for o in spec.requires_positive))
        for formula, why in spec.fallbacks:
            notes.append(f"fallback {_code(formula)} ({_cell(why)})")
        held = sorted(ratios.NOT_FOR.get(name, {}))
        if held:
            notes.append("not computed for: " + ", ".join(held))
        label = _cell(spec.label) + (f" (also `{'`, `'.join(aliases)}`)" if aliases else "")
        rows.append(f"| {_code(name)} | {UNITS[spec.unit]} | {_code(spec.formula)} | {label}"
                    f"{' - ' + '; '.join(notes) if notes else ''} |")
    return rows


def _metric_rows(group: str) -> list[str]:
    rows = []
    for name, spec in metrics.REGISTRY.items():
        ns = name.split(".")[0] if "." in name else ""
        if ns != group:
            continue
        kind = UNITS.get(spec.kind, spec.kind)
        when = "balance (a date)" if spec.is_point_in_time else "flow (a period)"
        rows.append(f"| {_code(name)} | {kind} | {spec.statement_type.value} | {when} | {_cell(spec.label)} |")
    return rows


def render() -> str:
    ind_as_xbrl.register()
    out = [
        "# Ratio and metric reference",
        "",
        "Generated by `scripts/gen_ratio_docs.py` from the registries; do not edit by hand.",
        "",
        "A ratio's formula is what the engine evaluates. Inputs are reported metrics (second table of "
        "each section), other ratios, `share_price`, `period_days`, `prior(x)` (the same metric one "
        "comparable period earlier) and `ttm(x)` (the sum over the periods making up a year). A missing "
        "input gives `None` with a reason, except those listed as treated as 0. A ratio marked "
        "\"not computed for\" a sector returns `None` with the reason for it; so does every ratio "
        "built on it (net debt, for instance, for a bank).",
        "",
    ]
    for group, title in GROUPS:
        r, m = _ratio_rows(group), _metric_rows(group)
        if not r and not m:
            continue
        out += [f"## {title}", ""]
        if r:
            out += ["### Ratios and derived quantities", "", "| Name | Unit | Formula | Meaning |",
                    "|---|---|---|---|", *r, ""]
        if m:
            out += ["### Reported metrics (inputs)", "", "| Name | Unit | Statement | Kind | Meaning |",
                    "|---|---|---|---|---|", *m, ""]
    out += [f"{len(ratios.FORMULAS)} ratios and derived quantities and {len(metrics.REGISTRY)} reported metrics.", ""]
    return "\n".join(out)


def main(argv: list[str]) -> int:
    text = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != text:
            print(f"{OUT} is out of date; run: python scripts/gen_ratio_docs.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
